[project]
name = "brf-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pymupdf==1.26.7",
    "pymupdf4llm==0.2.9",
    "tabulate==0.9.0",
]
